### ISSUE TITLE
Submit family to google/fonts

### ISSUE THREAD

**Issue by m4rc1e** [laerm0/Russolo#12]
Thanks for fixing #11. Can you send a pr to google/fonts for the family please?

Here's a quick guide if you need it, https://github.com/googlefonts/gf-docs/tree/master/MakingPullRequestsToGF

**Comment by laerm0** [comment]
Cool, thanks Marc, I am on it.

**Comment by laerm0** [comment]
Here you go: https://github.com/google/fonts/pull/2435

Thanks for coming back to this. :)
